INSERT INTO PET(NAME, SPECIES, AGE, DESCRIPTION, WEIGHT) VALUES('WHISKAS', 'CAT', 1, 'PLAYFUL CAT', 1.3);
INSERT INTO PET(NAME, SPECIES, AGE, DESCRIPTION, WEIGHT) VALUES('SPOT', 'DOG', 2, 'ENERGIC DOG', 5.2);
INSERT INTO PET(NAME, SPECIES, AGE, DESCRIPTION, WEIGHT) VALUES('SPIKE', 'DOG', 5, 'LOYAL DOG', 4.1);
INSERT INTO PET(NAME, SPECIES, AGE, DESCRIPTION, WEIGHT) VALUES('JOY', 'CAT', 3, 'LOYAL CAT', 1.3);